name: CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker build -t ghcr.io/buachailrua/zd2-1:1.0 .
      - run: docker push ghcr.io/buachailrua/zd2-1:1.0
      - run: docker build -t ghcr.io/buachailrua/zd2-2:1.0 .
      - run: docker push ghcr.io/buachailrua/zd2-2:1.0
      - run: ssh -o "StrictHostKeyChecking no" 'buachailrua-zd2-wtmvs9oti1l#gHb1wAHPzWo9Q.cmHlwh_xT9zr1m1WQX@buachailrua-zd2-wtmvs9oti1l.ssh.ws-eu107.gitpod.io' "cd /workspace/zd2 && docker compose pull && docker compose up -d"
      - name: send default message
        if: success()
        uses: appleboy/telegram-action@master
        with:
          message: "Сделано успешно"
          to: 808013173
          token: 6878790209:AAGwUdasDnQ8dmA2RfrnqRVhtZOcLO8yIsI
      - name: send default message
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          message: "Сделано ne успешно"
          to: 808013173
          token: 6878790209:AAGwUdasDnQ8dmA2RfrnqRVhtZOcLO8yIsI
